//go:generate goldigen --in "../types.yml" --out "dependency_injection.go" --package github.com/sawadeeeen/go-training/app/lib --function RegisterTypes --overwrite --nointeraction
package lib

import (
	"github.com/fgrosse/goldi"
	"github.com/sawadeeeen/go-training/app/service"
)

// RegisterTypes registers all types that have been defined in the file "../types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v1.0.1.
// It is however good practice to put this file under version control.
// See https://github.com/fgrosse/goldi for what is going on here.
func RegisterTypes(types goldi.TypeRegistry) {
	types.RegisterAll(map[string]goldi.TypeFactory{
		"injected": goldi.NewStructType(new(service.Injected)),
		"service":  goldi.NewStructType(new(service.ServiceImpl), "@injected"),
	})
}
